# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chavanga_development
  pool: 5
  username: root
  password: nfryflj
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chavanga_test
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chavanga_production
  pool: 5
  username: chavanga
  password: chavpass
  socket: /var/run/mysqld/mysqld.sock

